try with single e2e
Signed-off-by: Per Goncalves da Silva <pegoncal@redhat.com>

diff --git a/.github/workflows/e2e-tests.yml b/.github/workflows/e2e-tests.yml
--- a/.github/workflows/e2e-tests.yml
+++ b/.github/workflows/e2e-tests.yml
@@ -10,10 +10,10 @@ on:
   merge_group:
 jobs:
   e2e:
-    strategy:
-      fail-fast: false
-      matrix:
-        parallel-id: [0, 1, 2, 3]
+#    strategy:
+#      fail-fast: false
+#      matrix:
+#        parallel-id: [0, 1, 2, 3]
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
@@ -21,23 +21,30 @@ jobs:
         with:
           go-version-file: "go.mod"
       - run: mkdir -p artifacts
-      - run: make e2e-local E2E_TEST_CHUNK=${{ matrix.parallel-id }} E2E_TEST_NUM_CHUNKS=${{ strategy.job-total }} E2E_NODES=2 ARTIFACT_DIR=./artifacts/ SKIP='\[FLAKE\]'
+      - run: make e2e-local E2E_NODES=1 ARTIFACT_DIR=./artifacts/ SKIP='\[FLAKE\]'
       - name: Archive Test Artifacts # test results, failed or not, are always uploaded.
         if: ${{ always() }}
         uses: actions/upload-artifact@v3
         with:
-          name: e2e-test-output-${{ (github.event.pull_request.head.sha || github.sha) }}-${{ github.run_id }}-${{ matrix.parallel-id }}
+          name: e2e-test-output-${{(github.event.pull_request.head.sha||github.sha)}}-${{ github.run_id }}
           path: ${{ github.workspace }}/bin/artifacts/*
+#      - run: make e2e-local E2E_TEST_CHUNK=${{ matrix.parallel-id }} E2E_TEST_NUM_CHUNKS=${{ strategy.job-total }} E2E_NODES=2 ARTIFACT_DIR=./artifacts/ SKIP='\[FLAKE\]'
+#      - name: Archive Test Artifacts # test results, failed or not, are always uploaded.
+#        if: ${{ always() }}
+#        uses: actions/upload-artifact@v3
+#        with:
+#          name: e2e-test-output-${{ (github.event.pull_request.head.sha || github.sha) }}-${{ github.run_id }}-${{ matrix.parallel-id }}
+#          path: ${{ github.workspace }}/bin/artifacts/*
         # TODO: create job to combine test artifacts using code in https://github.com/operator-framework/operator-lifecycle-manager/pull/1476
-  e2e-tests:
-    if: ${{ always() }}
-    runs-on: ubuntu-latest
-    needs: e2e
-    steps:
-    - run: |
-        echo "Matrix result: ${{ needs.e2e.result }}"
-    - name: check individual matrix results
-      if: ${{ needs.e2e.result == 'failure' }}
-      run: |
-        echo 'Failure: at least one e2e matrix job has failed'
-        exit 1
+#  e2e-tests:
+#    if: ${{ always() }}
+#    runs-on: ubuntu-latest
+#    needs: e2e
+#    steps:
+#    - run: |
+#        echo "Matrix result: ${{ needs.e2e.result }}"
+#    - name: check individual matrix results
+#      if: ${{ needs.e2e.result == 'failure' }}
+#      run: |
+#        echo 'Failure: at least one e2e matrix job has failed'
+#        exit 1
